Increase the Pillow MAXBLOCK global.
We were encountering numerous but sporadic errors when saving
JPEG images with optimization turned on that presented as:

  IOError: encoder error -2 when writing image file

Turns out that this is a known issue (see
https://github.com/python-pillow/Pillow/issues/148).  Added some
code to dynamically scale MAXBLOCK value depending on image size.